[tool.poetry]
name = "cryptopals"
version = "0.1.0"
description = ""
authors = ["azuline <azuline@riseup.net>"]

[tool.poetry.dependencies]
python = "^3.7"
pycryptodome = "^3.9"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
